

name: Docker


on:
  push:
    
env:
  IMAGE_NAME: avapolos/postgres

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile -t $IMAGE_NAME:bdr
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push image
        run: docker push $IMAGE_NAME:bdr
